# Site settings
title: fuxiao511
email: wliang0371@gmail.com
description: Source of me.
localurl: "" # the subpath of your site, e.g. /blog/
url: http://fuxiao511.github.io # the base hostname & protocol for your site
me-img: "/img/HeadPicture.png"

twitter_username:
github_username: fuxiao511

# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: pygments

assets: http://fuxiao511.github.io/assets
baseurl: http://fuxiao511.github.io

# pagination
paginate: 10

# Markdown Processors
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - tables
    - lax_spacing
    - with_toc_data

tagline: A technology blog for myself.


##### Menu
menu:
  Home: /
  Archives: /archives
  About: /about
## you can create `tags` and `categories` folders in `../source`.
## And create a `index.md` file in each of them.
## set `front-matter`as
## layout: tags (or categories)
## title: tags (or categories)
## ---

#### Widgets
widgets:
- category
- tag
- links
- rss
## provide seven widgets:category,tag,rss,archive,tagcloud,links,weibo,douban


#### RSS
rss: /atom.xml ## RSS address.

#### Image
imglogo:
  enable: true             ## display image logo true/false.
  src: img/logo.png        ## `.svg` and `.png` are recommended,please put image into the theme folder `/jacman/source/img`.
favicon: img/favicon.ico   ## size:32px*32px,`.ico` is recommended,please put image into the theme folder `/jacman/source/img`.
apple_icon: img/jacman.jpg ## size:114px*114px,please put image into the theme folder `/jacman/source/img`.
author_img: img/author.jpg ## size:220px*220px.display author avatar picture.if don't want to display,please don't set this.
banner_img: #img/banner.jpg ## size:1920px*200px+. Banner Picture

#### index post is expanding or not
index:
  expand: true           ## default is unexpanding,so you can only see the short description of each post.
  excerpt_link: Read More

close_aside: false  #close sidebar in post page if true
mathjax: false      #enable mathjax if true

#### Author information
author:
  name: fuxiao511      ## e.g. wuchong Author name
  intro_line1:  "Hello ,I'm fuxiao."    ## your introduction on the bottom of the page
  github: fuxiao511    ## e.g. wuchong for https://github.com/wuchong
## if you set them, the corresponding  share button will show on the footer

#### Toc
toc:
  article: true   ## show contents in article.
  aside: true     ## show contents in aside.
## you can set both of the value to true of neither of them.
## if you don't want display contents in a specified post,you can modify `front-matter` and add `toc: false`.

#### Links
links:
  tcOops's Blog: http://spacenx.pw/

excerpt_separator: <!--more-->

#### Comment
duoshuo_shortname:    ## e.g. wuchong   your duoshuo short name.
disqus_shortname: fuxiao511    ## e.g. wuchong   your disqus short name.


#### Miscellaneous
fancybox: true        ## if you use gallery post or want use fancybox please set the value to true.
totop: true           ## if you want to scroll to top in every post set the value to true


gems:
 - jemoji
